spring.jackson.time-zone=Europe/Madrid
spring.application.name=misalud

# database connection
spring.datasource.url=jdbc:mysql://localhost:3307/misalud?useSSL=false&serverTimezone=Europe/Madrid&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret.key=supersecretoextremamentelargoyseguroparaHS512usadoenspringynoseporquetodavianofuncionaaversiestavezsifunciona

server.servlet.context-path=/misalud

# Hora a la que se elimina citas y medicaciones diariamente (01:00)
# cron.hour=0 0 1 * * *
